// =============================================
// fnBCRA_Transparencia_AllInOne
// ---------------------------------------------
// Consulta TODOS los endpoints del Régimen de
// Transparencia v1.0 del BCRA en una sola función
//
// Retorna:
//   Endpoint | OK | Filas | Error | Data (tabla tipada)
// =============================================
(optional codigoEntidad as nullable number) as table =>
let
    BaseUrl = "https://api.bcra.gob.ar/transparencia/v1.0/",

    // -----------------------------------------
    // Endpoints oficiales
    // -----------------------------------------
    Endpoints = {
        "CajasAhorros",
        "PaquetesProductos",
        "PlazosFijos",
        "Prestamos/Prendarios",
        "Prestamos/Hipotecarios",
        "Prestamos/Personales",
        "TarjetasCredito"
    },

    // -----------------------------------------
    // Función interna: inferir tipos
    // -----------------------------------------
    InferTypeFromValues = (vals as list) as type =>
    let
        AllAre = (pred as function) => List.AllTrue(List.Transform(vals, each pred(_))),

        CanParseDate =
            if AllAre(each _ is text) then
                List.AllTrue(List.Transform(vals, each (try Date.FromText(_) otherwise null) <> null))
            else false,

        CanParseDateTime =
            if AllAre(each _ is text) then
                List.AllTrue(List.Transform(vals, each (try DateTime.FromText(_) otherwise null) <> null))
            else false,

        result =
            if AllAre(each _ is number) then type number
            else if AllAre(each _ is logical) then type logical
            else if AllAre(each _ is date) then type date
            else if AllAre(each _ is datetime) then type datetime
            else if CanParseDate then type date
            else if CanParseDateTime then type datetime
            else type text
    in
        result,

    InferColumnTypes = (tbl as table, optional sampleSize as nullable number) as list =>
    let
        N = if sampleSize = null then 200 else sampleSize,
        cols = Table.ColumnNames(tbl),
        pairs =
            List.Transform(
                cols,
                (c as text) =>
                let
                    vals = List.FirstN(List.RemoveNulls(Table.Column(tbl, c)), N),
                    typ = if List.Count(vals) = 0 then type any else InferTypeFromValues(vals)
                in
                    {c, typ}
            )
    in
        pairs,

    // -----------------------------------------
    // Función interna: consultar un endpoint
    // -----------------------------------------
    FetchOne = (ep as text) as record =>
    let
        Raw =
            try
                Web.Contents(
                    BaseUrl,
                    [
                        RelativePath = ep,
                        Query = if codigoEntidad <> null then [codigoEntidad = Text.From(codigoEntidad)] else null,
                        Headers = [Accept="application/json"],
                        Timeout = #duration(0,0,30,0)
                    ]
                ),

        Json =
            if Raw[HasError] then
                null
            else
                let
                    j1 = try Json.Document(Raw[Value])
                in
                    if j1[HasError] = false then
                        j1[Value]
                    else
                        let
                            txt = try Text.FromBinary(Raw[Value], TextEncoding.Utf8) otherwise null,
                            j2 = if txt <> null then try Json.Document(Text.TrimStart(txt)) else null
                        in
                            if j2 <> null and j2[HasError] = false then
                                j2[Value]
                            else
                                null,

        Results =
            if Json <> null and Value.Is(Json, type record) and Record.HasFields(Json, "results") then
                Json[results]
            else if Json <> null and Value.Is(Json, type list) then
                Json
            else
                null,

        TableRaw =
            if Results <> null then
                Table.FromList(Results, Splitter.SplitByNothing(), {"Data"})
            else
                null,

        TableExpanded =
            if TableRaw <> null and Table.RowCount(TableRaw) > 0 and Value.Is(TableRaw{0}[Data], type record) then
                Table.ExpandRecordColumn(TableRaw, "Data", Record.FieldNames(TableRaw{0}[Data]))
            else
                TableRaw,

        // -----------------------------------------
        // Tipado dinámico
        // -----------------------------------------
        Typed =
            if TableExpanded <> null then
                let
                    Types = InferColumnTypes(TableExpanded),
                    t =
                        Table.TransformColumns(
                            TableExpanded,
                            List.Transform(
                                Types,
                                (p) =>
                                    let col = p{0}, typ = p{1} in
                                    if typ = type date then
                                        {col, each try Date.From(_) otherwise try Date.FromText(_) otherwise null, type date}
                                    else if typ = type datetime then
                                        {col, each try DateTime.From(_) otherwise try DateTime.FromText(_) otherwise null, type datetime}
                                    else
                                        {col, each _, typ}
                            ),
                            null,
                            MissingField.Ignore
                        )
                in t
            else
                null,

        ok = Typed <> null,
        filas = if ok then Table.RowCount(Typed) else null,
        err =
            if Raw[HasError] then "Error HTTP"
            else if Json = null then "Error parse JSON"
            else if Results = null then "Sin results"
            else null

    in
        [
            Endpoint = ep,
            OK = ok,
            Filas = filas,
            Error = err,
            Data = Typed
        ],

    // -----------------------------------------
    // Ejecutar todos los endpoints
    // -----------------------------------------
    Result =
        Table.FromRecords(
            List.Transform(Endpoints, each FetchOne(_))
        )

in
    Result
