let
    fxExtraerIdentificadoresM =
    (fnCodigo as text) as record =>
    let
        // =========================================
        // 0. Entrada
        // =========================================
        // Texto que contiene código M (Power Query)
        Texto = fnCodigo,

        // =========================================
        // 1. Definición de separadores (parser básico)
        // =========================================
        // Se definen explícitamente caracteres que delimitan tokens
        chTAB = Character.FromNumber(9),
        chLF  = Character.FromNumber(10),
        chCR  = Character.FromNumber(13),

        Separadores = {
            " ", chTAB, chLF, chCR,
            ",", ";", "=", "(", ")", "{", "}", "[", "]",
            "+", "-", "*", "/", "&", "|", "<", ">", ":"
        },

        // =========================================
        // 2. Función auxiliar: limpieza segura de texto
        // =========================================
        // Evita errores del motor de PQ con Text.Trim (multi-char)
        // Se aplica trim carácter por carácter
        TrimSeguro = (t as nullable text) as text =>
            let
                base = if t = null then "" else Text.Trim(t),
                toTrim = {" ", chTAB, chLF, chCR, ")", "(", "}", "{", "]", "[", """", "'", ",", ";"},
                res = List.Accumulate(toTrim, base, (state, c) => Text.Trim(state, c))
            in
                Text.Trim(res),

        // =========================================
        // 3. Extracción hacia atrás
        // =========================================
        // Dada una posición en el texto, identifica el token previo
        ExtraerAtras = (pos as number) as text =>
            let
                SubTexto = Text.Start(Texto, pos),
                UltimaPos =
                    List.Max(
                        List.Transform(
                            Separadores,
                            each Text.PositionOf(SubTexto, _, Occurrence.Last)
                        )
                    ),
                token = Text.Middle(SubTexto, UltimaPos + 1)
            in
                TrimSeguro(token),

        // =========================================
        // 4. Extracción hacia adelante
        // =========================================
        // Permite capturar la parte derecha del identificador (ej: ".Monday")
        ExtraerAdelante = (pos as number) as text =>
            let
                SubFwd = Text.Range(Texto, pos),

                posiciones =
                    List.Transform(
                        Separadores,
                        (s) =>
                            let p = Text.PositionOf(SubFwd, s, Occurrence.First)
                            in if p < 0 then 999999999 else p
                    ),

                corte = List.Min(posiciones),

                token =
                    if corte = 999999999
                    then SubFwd
                    else Text.Start(SubFwd, corte)
            in
                TrimSeguro(token),

        // =========================================
        // 5. Detección de funciones (pattern: nombre())
        // =========================================
        // Se detectan mediante el carácter "("
        PosicionesFunciones = Text.PositionOf(Texto, "(", Occurrence.All),

        CandidatosFunciones =
            List.Transform(
                PosicionesFunciones,
                each ExtraerAtras(_)
            ),

        // Se filtran solo los que tienen formato Namespace.Funcion
        Funciones =
            List.Select(
                CandidatosFunciones,
                each Text.Contains(_, ".")
            ),

        // =========================================
        // 6. Detección de enums / constantes (pattern: A.B)
        // =========================================
        PosicionesPunto = Text.PositionOf(Texto, ".", Occurrence.All),

        CandidatosPunto =
            List.Transform(
                PosicionesPunto,
                (p) =>
                    let
                        izq = ExtraerAtras(p),
                        der = ExtraerAdelante(p + 1),
                        id  = if izq <> "" and der <> "" then izq & "." & der else ""
                    in
                        id
            ),

        // =========================================
        // 7. Limpieza de falsos positivos
        // =========================================
        // Elimina:
        // - URLs
        // - concatenaciones inválidas
        // - números decimales tipo "1.23"
        EsNumero = (t as text) as logical =>
            (try Number.FromText(t) otherwise null) <> null,

        EnumsYConstantes =
            List.Select(
                CandidatosPunto,
                each
                    _ <> ""
                    and Text.Contains(_, ".")
                    and not Text.Contains(Text.Lower(_), "http")
                    and not Text.Contains(_, "://")
                    and not (
                        let parts = Text.Split(_, ".")
                        in List.Count(parts) = 2
                           and EsNumero(parts{0})
                           and EsNumero(parts{1})
                    )
            ),

        // =========================================
        // 8. Consolidación de identificadores
        // =========================================
        // Se combinan funciones + enums y se eliminan duplicados
        ListaNombres =
            List.Sort(
                List.Distinct(
                    List.Combine({Funciones, EnumsYConstantes})
                )
            ),

        // =========================================
        // 9. Evaluación dinámica
        // =========================================
        // Se resuelve cada identificador contra el entorno global (#shared)
        Valores =
            List.Transform(
                ListaNombres,
                each try Expression.Evaluate(_, #shared) otherwise null
            ),

        // =========================================
        // 10. Construcción del resultado final
        // =========================================
        // Se arma un record Nombre = Valor
        // Se eliminan los identificadores no resolubles (null)
        Resultado =
            let
                r = Record.FromList(Valores, ListaNombres),
                nombres = Record.FieldNames(r),
                nombresValidos =
                    List.Select(
                        nombres,
                        each Record.Field(r, _) <> null
                    )
            in
                Record.SelectFields(r, nombresValidos)

    in
        Resultado,


    // =========================================
    // Documentación de la función
    // =========================================
    Documentacion =
        type function
        (
            fnCodigo as text
        )
        as record
        meta
        [
            Documentation.Name = "fxExtraerIdentificadoresM",

            Documentation.LongDescription =
"Función que analiza código M (Power Query) en formato texto y devuelve un record con todos los identificadores necesarios para evaluar la expresión usando Expression.Evaluate.

Incluye:
- Funciones (Table.*, List.*, Text.*, Date.*, etc.)
- Enumeraciones (Day.Monday, Order.Ascending, MissingField.Ignore, etc.)
- Constantes (ExtraValues.Error, etc.)

Uso principal:
- Construcción automática de environments controlados para Expression.Evaluate
- Eliminación de dependencia de #shared completo
- Mejora en trazabilidad, control y seguridad del código

Funcionamiento:
1. Detecta funciones mediante '('
2. Detecta identificadores con '.' (enums/constantes)
3. Extrae tokens hacia atrás y adelante
4. Limpia falsos positivos (URLs, números, ruido)
5. Evalúa los identificadores contra #shared
6. Devuelve un record solo con los valores válidos

Salida:
- Record: [ Identificador = ValorReal ]

Ejemplo:
fxExtraerIdentificadoresM(""Table.SelectRows(Source, each [A] > 0)"")",

            Documentation.Category = "Power Query / Parsing",
            Documentation.Source   = "Local",
            Documentation.Author   = "Cristian Luongo",
            Documentation.Version  = "1.0.0"
        ]

in
    Value.ReplaceType(fxExtraerIdentificadoresM, Documentacion)
