let
    // =========================================
    // 1. Obtener el HTML de la página
    // =========================================
    UrlFuente = "https://www.facpce.org.ar/indices-facpce/",
    Html = Web.Contents(UrlFuente),

    // =========================================
    // 2. Extraer todos los links (<a.archive-download-container>) del HTML
    // Html.Table permite parsear el DOM de forma estructurada
    // =========================================
    LinksExtraidos = Html.Table(
        Html,
        {
            {"Href", "a.archive-download-container", each [Attributes][href]}
        }
    ),

    // =========================================
    // 3. Filtrar únicamente links que apunten a archivos Excel
    // =========================================
    LinksExcel = Table.SelectRows(
        LinksExtraidos,
        each Text.Contains([Href], ".xlsx")
    ),

    // =========================================
    // 4. Obtener la URL del archivo a descargar
    // Se toma el primer resultado encontrado
    // =========================================
    UrlExcel = LinksExcel{0}[Href],

    // =========================================
    // 5. Descargar el archivo Excel (binario)
    // =========================================
    ArchivoExcel = Web.Contents(UrlExcel),

    // =========================================
    // 6. Leer la estructura del archivo Excel
    // =========================================
    ContenidoExcel = Excel.Workbook(ArchivoExcel)
in
ContenidoExcel
