let
    // =========================================
    // 1. Obtener el HTML de la página
    // =========================================
    UrlFuente = "https://www.facpce.org.ar/indices-facpce/",
    Html = Web.Contents(UrlFuente),

    // =========================================
    // 2. Extraer todos los links (<a.archive-download-container>) del HTML
    // Html.Table permite parsear el DOM de forma estructurada
    // =========================================
    LinksExtraidos = Html.Table(
        Html,
        {
            {"Href", "a.archive-download-container", each [Attributes][href]}
        }
    ),

    // =========================================
    // 3. Filtrar únicamente links que apunten a archivos Excel
    // =========================================
    LinksExcel = Table.SelectRows(
        LinksExtraidos,
        each Text.Contains([Href], ".xlsx")
    ),

    // =========================================
    // 4. Obtener la URL del archivo a descargar
    // Se toma el primer resultado encontrado
    // =========================================
    UrlExcel = LinksExcel{0}[Href],

    // =========================================
    // 5. Descargar el archivo Excel (binario)
    // =========================================
    ArchivoExcel = Web.Contents(UrlExcel),

    // =========================================
    // 6. Leer la estructura del archivo Excel
    // =========================================
    ContenidoExcel = Excel.Workbook(ArchivoExcel),

    // =========================================
    // 7. Transformar cada tabla del Excel
    // Limpieza y normalización de datos
    // =========================================
    TransformarTablas = Table.TransformColumns(
        ContenidoExcel,
        {
            {
                "Data",
                each
                    let
                        // Seleccionar columnas relevantes
                        ColumnasRelevantes = Table.SelectColumns(_, {"Column1", "Column2"}),

                        // Eliminar filas iniciales y promover encabezados
                        Encabezados = Table.PromoteHeaders(
                            Table.Skip(ColumnasRelevantes, 2)
                        ),

                        // Eliminar filas vacías
                        FilasValidas = Table.SelectRows(
                            Encabezados,
                            each not List.IsEmpty(
                                List.RemoveMatchingItems(Record.FieldValues(_), {"", null})
                            )
                        ),

                        // Quitar totales u observaciones finales
                        SinTotales = Table.RemoveLastN(FilasValidas, 2),

                        // Tipado explícito (más robusto que TransformColumns genérico)
                        Tipos = Table.TransformColumnTypes(
                            SinTotales,
                            {
                                {"MES", type date},
                                {"IPC NACIONAL EMPALME IPIM", type number}
                            }
                        )
                    in
                        Tipos,

                type table [MES = date, #"IPC NACIONAL EMPALME IPIM" = number]
            }
        }
    ),

    // =========================================
    // 8. Seleccionar la hoja específica requerida
    // =========================================
    HojaFinal = TransformarTablas{
        [Item = "ipc empalme ipim", Kind = "Sheet"]
    }[Data]
in
    HojaFinal
