let
Replace_Type = ( Table as table ) as table =>
    let 
    Sample = Table.FirstN(Table,10),
    Columns = Table.ToColumns(Sample),
    Types = List.Transform(Columns, each List.Distinct(List.Transform(List.Select(_, (ListItem)=>ListItem<>null), (i)=> try Value.Type( Date.From(i)) otherwise try Value.Type( Number.From(i)) otherwise Value.Type(i)))),
    NewTypes = List.Transform(Types, each if List.Count(_) = 1 then _{0} else type any),
    Typed = Table.TransformColumnTypes(Table,List.Zip({Table.ColumnNames(Table), NewTypes}))
    in
    Typed
in
Replace_Type
