// ============================================================
// CONSULTA: Categorías de Monotributo - ARCA (ex AFIP)
// ============================================================
// Fuente:   https://www.afip.gob.ar/monotributo/categorias.asp
// Autor:    Cristian Luongo
// Versión:  1.0
//
// DESCRIPCIÓN:
//   Extrae la tabla de categorías y valores del monotributo
//   directamente desde el sitio oficial de ARCA, renderizando
//   el HTML completo con Web.BrowserContents para capturar
//   contenido generado dinámicamente.
//
// ESTRATEGIA DE SELECCIÓN DE CELDAS:
//   Se usa el atributo data-title de cada <td> como selector,
//   ya que es el texto descriptivo para la vista mobile y es
//   menos propenso a cambios que los id internos de la tabla.
//   La columna Categ. es un caso especial: usa <th scope='row'>
//   en lugar de <td>, por lo que requiere un selector distinto.
//
// MANTENIMIENTO:
//   Si ARCA modifica la estructura HTML de la tabla, los puntos
//   más probables de ruptura son:
//   1. Los valores de data-title en los <td> → ajustar los
//      selectores en el bloque de Html.Table
//   2. El atributo scope='row' del <th> de categoría → ajustar
//      el primer selector
//   3. El número de categorías (hoy 11) → ajustar el umbral
//      en el paso Validacion
// ============================================================

let
    // ----------------------------------------------------------
    // PASO 1: Obtener el HTML completo de la página
    // ----------------------------------------------------------
    // Web.BrowserContents renderiza JavaScript antes de devolver
    // el HTML, a diferencia de Web.Contents que solo trae el HTML
    // estático. Necesario porque la tabla puede cargarse via JS.
    // ----------------------------------------------------------
    Origen = Web.BrowserContents("https://www.afip.gob.ar/monotributo/categorias.asp"),

    // ----------------------------------------------------------
    // PASO 2: Extraer la tabla con Html.Table
    // ----------------------------------------------------------
    // List.Zip combina la lista de nombres de columna con la lista
    // de selectores CSS, generando los pares {nombre, selector}
    // que requiere Html.Table.
    // RowSelector apunta a las filas de datos del <tbody>,
    // excluyendo los encabezados del <thead>.
    // ----------------------------------------------------------
    TablaFinal = Html.Table(
        Origen,
        List.Transform(
            List.Zip({
                // Nombres de columna que tendrá la tabla resultante
                {
                    "Categ.",
                    "Ingresos brutos",
                    "Sup. Afectada",
                    "Energía eléctrica consumida anualmente",
                    "Alquileres devengados anualmente",
                    "Precio unitario máximo",
                    "Impuesto integrado - Loc/Servicios",
                    "Impuesto integrado - Venta muebles",
                    "Aportes al SIPA",
                    "Aportes obra social",
                    "Total - Loc/Servicios",
                    "Total - Venta muebles"
                },
                // Selectores CSS correspondientes a cada columna
                // NOTA: si ARCA modifica los data-title, actualizar aquí
                {
                    "th[scope='row']",                                                           // Categ.: usa <th>, no <td>
                    "td[data-title='Ingresos brutos (****)']",
                    "td[data-title='Superficie Afectada (*)']",
                    "td[data-title='Energía Eléctrica Consumida Anualmente']",
                    "td[data-title='Alquileres Devengados Anualmente']",
                    "td[data-title='Precio unitario máximo para venta de Cosas Muebles']",
                    "td[data-title='Impuesto Integrado: Locaciones y/o Prestaciones de Servicios']",
                    "td[data-title='Impuesto Integrado: Venta de Cosas Muebles']",
                    "td[data-title='Aportes al SIPA (**)']",
                    "td[data-title='Aportes Obra Social (***)']",
                    "td[data-title='Total: Locaciones y/o prestaciones de servicios']",
                    "td[data-title='Total: Venta de Cosas Muebles']"
                }
            }),
            each {_{0}, _{1}}
        ),
        [RowSelector = "tbody tr"]
    ),

    // ----------------------------------------------------------
    // PASO 3: Validación de estructura
    // ----------------------------------------------------------
    // Si ARCA modifica el HTML y los selectores dejan de funcionar,
    // la tabla devuelve filas vacías o nulas sin lanzar error.
    // Esta validación hace el fallo explícito y descriptivo.
    // Umbral: 11 categorías (A→K). Ajustar si agregan nuevas.
    // ----------------------------------------------------------
    Validacion = if Table.RowCount(TablaFinal) < 11
        then error "La tabla de ARCA devolvió menos filas de las esperadas. Verificar si cambió la estructura del HTML."
        else TablaFinal,

    // ----------------------------------------------------------
    // PASO 4: Limpieza de espacios
    // ----------------------------------------------------------
    // Algunas celdas del HTML tienen espacios sobrantes al inicio
    // o al final (ej: "$129.045,32  " en categoría F).
    // Text.Trim se aplica a todas las columnas de forma dinámica.
    // ----------------------------------------------------------
    TablaLimpia = Table.TransformColumns(
        Validacion,
        List.Transform(
            Table.ColumnNames(Validacion),
            each {_, Text.Trim}
        )
    ),

    // ----------------------------------------------------------
    // PASO 5: Función de conversión de moneda a número
    // ----------------------------------------------------------
    // Los valores vienen en formato argentino: "$10.277.988,13"
    //   . = separador de miles
    //   , = separador decimal
    // Pasos de normalización:
    //   1. Quitar el signo $
    //   2. Eliminar los . separadores de miles
    //   3. Reemplazar el | por . para restaurar el decimal
    // ----------------------------------------------------------
    ParsearPeso = (valor as text) as number =>
        let
            SinSigno    = Text.TrimStart(Text.Trim(valor), "$"),
            SinPuntos   = Text.Replace(SinSigno, ".", ""),
            Normalizado = Text.Replace(SinPuntos, "|", ".")
        in
            Number.FromText(Normalizado),

    // ----------------------------------------------------------
    // PASO 6: Conversión de tipos
    // ----------------------------------------------------------
    // Solo se convierten a número las columnas monetarias.
    // "Categ." y las columnas de superficie/energía se dejan
    // como texto porque sus valores no son numéricos puros
    // (ej: "Hasta 30 m2", "Hasta 3330 Kw").
    // ----------------------------------------------------------
    ColsNumericas = {
        "Ingresos brutos",
        "Alquileres devengados anualmente",
        "Precio unitario máximo",
        "Impuesto integrado - Loc/Servicios",
        "Impuesto integrado - Venta muebles",
        "Aportes al SIPA",
        "Aportes obra social",
        "Total - Loc/Servicios",
        "Total - Venta muebles"
    },

    TablaFinalTipada = Table.TransformColumns(
        TablaLimpia,
        List.Transform(
            ColsNumericas,
            each {_, ParsearPeso, type number}
        )
    )

in
    TablaFinalTipada
